AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PR Request Flask App with SNS Integration

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
  SnsTopicArn:
    Type: String
    Default: arn:aws:sns:us-east-1:238338230919:pr-review-standard-dev

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    MemorySize: 128

Resources:
  PrRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handler.handler
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SnsTopicArn
          STAGE: !Ref Stage
      Events:
        PrRequestApi:
          Type: Api
          Properties:
            Path: /prrequest
            Method: POST
            RestApiId: !Ref ApiGateway
        HealthApi:
          Type: Api
          Properties:
            Path: /health
            Method: GET
            RestApiId: !Ref ApiGateway

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      DefinitionBody:
        swagger: "2.0"
        paths:
          /prrequest:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PrRequestFunction.Arn}/invocations"
                httpMethod: POST
                type: aws_proxy
          /health:
            get:
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PrRequestFunction.Arn}/invocations"
                httpMethod: POST
                type: aws_proxy

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"